# import

In [26]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [27]:
# for reproducibility
torch.manual_seed(1)

# Training Data

In [6]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

In [7]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [35]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


ValueError: only one element tensors can be converted to Python scalars

# Computing the Hypothesis

In [17]:
W = torch.zeros((2,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [18]:
h = 1 / (1 + torch.exp(-(x_train.matmul(W)+b)))
h = torch.sigmoid(x_train.matmul(W)+b)

In [19]:
print(h)
print(h.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
torch.Size([6, 1])


# Computing the Cost Function

In [23]:
losses = -(y_train*torch.log(h) + (1-y_train)*torch.log(1-h))

In [24]:
cost = losses.mean()
print(cost)

tensor(0.6931, grad_fn=<MeanBackward0>)


In [34]:
cost = F.binary_cross_entropy(h,y_train)
print(cost)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)


0.6931471824645996

# Training Procedure

In [37]:
# optimizer 설정
optimizer = optim.SGD([W,b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs +1):
    
    # Cost 계산
    h = torch.sigmoid(x_train.matmul(W)+b)
    cost = F.binary_cross_entropy(h,y_train)
    
    # Cost로 h(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그 출력
    if epoch%100 == 0:
        print('Epoch {:4d}/{} Cost: {:6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 1.009292
Epoch  100/1000 Cost: 0.133813
Epoch  200/1000 Cost: 0.080325
Epoch  300/1000 Cost: 0.057738
Epoch  400/1000 Cost: 0.045202
Epoch  500/1000 Cost: 0.037195
Epoch  600/1000 Cost: 0.031625
Epoch  700/1000 Cost: 0.027520
Epoch  800/1000 Cost: 0.024366
Epoch  900/1000 Cost: 0.021866
Epoch 1000/1000 Cost: 0.019834


# Evaluation

In [50]:
h = torch.sigmoid(x_train.matmul(W)+b)
pred = (h >= 0.5).type(torch.ByteTensor)
print(pred)
print(y_train)

tensor([[0],
        [0],
        [0],
        [1],
        [1],
        [1]], dtype=torch.uint8)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
